package com.ylc.controller;

import com.ylc.model.UserTest;
import com.ylc.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * author: tree
 * version: 1.0
 * date: 2017/12/29 15:34
 * description: xxx
 * own: Aratek
 */
@RestController // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired      // This means to get the bean called userRepository
                    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping("/add")
    public String addNewUsr(@RequestParam String name,@RequestParam String email) {
        UserTest userTest = new UserTest();
        userTest.setName("ylc");
        userTest.setEmail("jkkkklllipp");
        userRepository.save(userTest);
        return "saved";
    }

    @GetMapping("/all")
    public Iterable<UserTest> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
